[alias]
coverage_0 = ["llvm-cov", "nextest", "--no-report", "--output-dir", "./target/coverage", "--features", ""]
coverage_1 = ["llvm-cov", "nextest", "--no-report", "--output-dir", "./target/coverage", "--features", "debug"]
coverage_2 = ["llvm-cov", "nextest", "--no-report", "--output-dir", "./target/coverage", "--features", "fn_res"]
coverage_3 = ["llvm-cov", "nextest", "--no-report", "--output-dir", "./target/coverage", "--features", "fn_res fn_res_mut"]
coverage_4 = ["llvm-cov", "nextest", "--no-report", "--output-dir", "./target/coverage", "--features", "fn_res fn_res_mut fn_res_once"]
coverage_5 = ["llvm-cov", "nextest", "--no-report", "--output-dir", "./target/coverage", "--features", "debug fn_res"]
coverage_6 = ["llvm-cov", "nextest", "--no-report", "--output-dir", "./target/coverage", "--features", "debug fn_res fn_res_mut fn_res_once high_arg_count"]
coverage_open = 'llvm-cov --no-run --open --output-dir ./target/coverage'
